---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-development
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
