---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infisical-secret-store
  namespace: flux-system
spec:
  interval: 5m
  path: ./secret-store/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
