---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: template-api-go-infisical-managed
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical-secret-store
  target:
    name: template-api-go
  data:
    - remoteRef:
        key: redis_host
      secretKey: redis_host
    - remoteRef:
        key: redis_password
      secretKey: redis_password
