---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-auth-credentials
            namespace: default
          clientSecret:
            key: clientSecret
            name: infisical-auth-credentials
            namespace: default
      secretsScope:
        environmentSlug: development
        expandSecretReferences: false
        projectSlug: k8s-cluster
        recursive: true
      hostAPI: https://app.infisical.com
