---
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
configMapGenerator:
  - name: template-api-kotlin-config
    files:
      - application.yml
    options:
      disableNameSuffixHash: true
resources:
  - ../base
  - external-secret.yaml
