extends: default

exclude:
  - .github/**

rules:
  braces:
    level: error
    min-spaces-inside: 1
    max-spaces-inside: 1
  brackets:
    level: error
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    level: warning
    min-spaces-from-content: 2
  document-start:
    level: warning
  line-length:
    level: error
    max: 80
  truthy:
    level: error
