---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /template-api-go/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: template-api-go
  name: template-api-go
spec:
  ports:
    - name: TCP
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: template-api-go
  type: ClusterIP
