---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-default
  namespace: flux-system
spec:
  interval: 5m
  path: ./gateways/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./gateways/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
