---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: template-api-java-infisical-managed
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical-secret-store
  target:
    name: template-api-java
  data:
    - remoteRef:
        key: api_service_url
      secretKey: api_service_url
    - remoteRef:
        key: redis_host
      secretKey: redis_host
    - remoteRef:
        key: redis_password
      secretKey: redis_password
    - remoteRef:
        key: sb_admin_client_url
      secretKey: sb_admin_client_url
    - remoteRef:
        key: api_legacy_url
      secretKey: api_legacy_url
