name: Lint and Validate Kubernetes manifests

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint + Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint . --config-file .github/workflows/.yamllint.yml
      - name: Run kubeval
        uses: instrumenta/kubeval-action@master

      - name: Kustomize setup
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/kustomize
      - name: Kustomization manifests validation
        run: |
          echo -e "Checking Kustomization manifests...\n"
          find . -name kustomization.yaml -exec dirname {} \; | while read dir; do
            echo "Validating $dir"
            kustomize build "$dir" >/dev/null
          done
