name: Lint and Validate Kubernetes manifests

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint + Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint . --config-file .github/lint/.yamllint.yml

      - name: kubeconform setup
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install kubeconform
          brew link kubeconform
      - name: kubeconform manifests validation
        run: |
          echo "Checking Kubernetes manifests..."
          find . -type f -path "*/base/*.yaml" ! -name "kustomization.yaml" -exec kubeconform -summary {} \;
          find . -type f -path "/ingress/*.yaml" ! -name "kustomization.yaml" -exec kubeconform -summary {} \;

      - name: Kustomize setup
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/kustomize
      - name: Kustomization manifests validation
        run: |
          echo -e "Checking Kustomization manifests...\n"
          find . -name kustomization.yaml -exec dirname {} \; | while read dir; do
            echo "Validating $dir"
            kustomize build "$dir" >/dev/null
          done
